 - name: "install nginx"
   yum: name=http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
   tags: install_nginx_repo

 - name: "install nginx"
   yum: name=nginx state=latest enablerepo=nginx
   tags: install_nginx

 - template: src=./template/nginx.j2 dest=/etc/nginx/conf.d/{{item.hostname}}.conf owner=nginx group=nginx mode=0644
   with_items:
    - { hostname: 'sample_host' }
   tags: nginx_conf
