- hosts: target
  become: yes
  roles:
    - role: cron
      tags: cron
    - role: logrotate
      tags: logrotate
    - role: zabbix
      tags: zabbix
    - role: git
      tags: git
    - role: port
      tags: port
    - role: alias
      tags: alias
    - role: serverspec
      tags: serverspec
    - role: ntp
      tags: ntp
