- hosts: target
  remote_user: root
  vars_files:
    - ./vars/mysqlinfo.yml
  tasks: 
   - name: "install mysql"
     yum: name={{item}} state=latest
     with_items:
        - mysql
        - mysql-server
        - MySQL-python

   - name: " service mysqld on"   
     service: name=mysqld state=started enabled=yes
 
   - name: " my.cnf cp"   
     command: " cp -ip /etc/my.cnf /etc/my.cnf.org " 

   - name: " revise  my.cnf"   
     ini_file: dest='/etc/my.cnf' section='{{item.section}}' option='{{item.option}}' value='{{item.replaced_value}}'
     with_items:
      - { section: 'mysql', option: 'default-character-set', replaced_value: 'utf8'  }
      - { section: 'client', option: 'default-character-set', replaced_value: 'utf8'  }
      - { section: 'mysqld', option: 'default-character-set', replaced_value: 'utf8'  }
      - { section: 'mysqld_safe', option: 'default-character-set', replaced_value: 'utf8'}

   - name: " create mysql_db"
     mysql_db: name={{dbname}} state=present encoding=utf8
  
   - name: " create mysql_user"
     mysql_user: name={{dbuser}} password={{dbpass}} priv={{dbname}}.*:ALL host={{dbhost}} state=present
     
