- hosts: target
  remote_user: remote_user
  become: yes
  roles:
    - role: nginx
      tags: nginx
    - role: perl
      tags: perl
    - role: cpan
      tags: cpan
    - role: mysql
      tags: mysql