 - name: start_firewall
   systemd:
     name: firewalld.service
     state: started
     daemon_reload: yes
     enabled: yes
   tags: start_firewall

 - firewalld: service={{item}} permanent=true state=enabled immediate=true
   with_items:
      - http
      - mysqld
      - ssh
   tags: set_port
