 - name: "yum update"
   command: "yum -y update"
   tags: yum_update

 - name: "python"
   yum: name=libselinux-python state=latest
   tags: python

 - name: "basic library"
   yum: name={{item}} state=latest
   with_items:
      - man
      - sudo
      - vim-enhanced
      - wget
      - git
      - tree
      - gcc
      - make
      - autoconf
      - patch
      - curl-devel
      - openssl-devel
      - mod_ssl
      - mysql-devel
      - httpd-devel
      - automake
      - net-tools
      - sysstat
      - iotop
   tags: basic_library

 - name: "repository"
   yum: name={{item}}
   with_items:
      - epel-release
      - http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
   tags: repo
