 - name: "remove yum git"
   yum: name=git state=remove
   tags: remove_git

 - name: "import yum"
   yum: name={{item}} state=latest
   with_items:
      - curl-devel
      - expat-devel
      - gettext-devel
      - openssl-devel
      - zlib-devel
      - perl-ExtUtils-MakeMaker
   tags: import_prev_lib

 - name: "install git"
   shell: >
     cd /usr/local
     wget https://www.kernel.org/pub/software/scm/git/git-{{git_version}}.tar.gz
     tar zxvf git-{{git_version}}.tar.gz
     cd git-{{git_version}}
     ./configure --prefix=/usr/local
     make prefix=/usr/local all
     make prefix=/usr/local install;
   tags: install_git