 - name: "remove yum git"
   yum: name=git state=removed
   tags: remove_git

 - name: "import yum"
   yum: name={{item}} state=latest
   with_items:
      - curl-devel
      - expat-devel
      - gettext-devel
      - openssl-devel
      - zlib-devel
      - perl-ExtUtils-MakeMaker
   tags: import_prev_lib

 - name: "install git"
   shell: >
     cd /usr/local;
     wget https://www.kernel.org/pub/software/scm/git/git-{{git_version}}.tar.gz;
     tar zxvf git-{{git_version}}.tar.gz;
     cd git-{{git_version}};
     ./configure --prefix=/usr/local;
     make prefix=/usr/local all;
     make prefix=/usr/local install;
   tags: install_git

 - git_config: name={{item.name}} scope=global value={{ item.value }}
   with_items:
      - { name: 'user.name' , value: 'Matsu' }
      - { name: 'user.email' , value: 'matsumoto@donow.jp' }
      - { name: 'color.ui' , value: true }
      - { name: 'core.editor' , value: 'vim' }
      - { name: 'core.autocrlf' , value: 'input' }
   tags: git_config
