 - name: " import remi-repo rpm "
   yum: name=http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
   tags: import_remi_repo

 - name: "install php"
   yum: name={{item}} state=latest enablerepo=remi,remi-php56
   with_items:
      - php
      - php-opcache
      - php-devel
      - php-mbstring
      - php-mcrypt
      - php-mysqlnd
      - php-phpunit-PHPUnit
      - php-pecl-xdebug
      - php-pecl-xhprof
      - php-intl
      - php-common
   tags: install_php

 - name: 'install_php-fpm'
   yum: name=php-fpm state=latest
   tags: intall_php_fpm

 - service: name=php-fpm state=started enabled=yes
   tags: service_php_fpm