- name: aws epel install
  shell: amazon-linux-extras install epel
  tags: aws_epel

- name: "repository"
  yum: name={{item}}
  with_items:
    - http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
  tags: aws_other_repo
