 - name: " import remi-repo rpm "
   yum: name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
   tags: import_remi_repo

 - name: "install php"
   yum: name={{item}} state=latest enablerepo=epel,remi-php74
   with_items:
      - php
      - php-cli
      - php-devel
      - php-mbstring
      - php-mcrypt
      - php-mysqlnd
      - php-phpunit-PHPUnit
      - php-pecl-xdebug
      - php-pecl-xhprof
      - php-intl
      - php-common
   tags: install_php

 - name: "php.ini cp"
   command: " cp -ip /etc/php.ini /etc/php.ini.org "
   tags: php_ini

 - name: "php.ini replace"
   replace: dest='/etc/php.ini' regexp='{{item.pattern}}' replace='{{item.replaced_value}}' backup=no
   with_items:
     - { pattern: ';mbstring.language = Japanese', replaced_value: 'mbstring.language = Japanese' }
     - { pattern: ';date.timezone =', replaced_value: 'date.timezone = Asia/Tokyo' }
     - { pattern: ';mbstring.internal_encoding =', replaced_value: 'mbstring.internal_encoding = UTF-8' }
   tags: php_ini_replace

 - name: 'install_memcached'
   #リポジトリ指定しないと古いリポジトリから読み込んでしまう
   yum: name={{item}} state=latest enablerepo=remi-php74,remi,epel
   with_items:
      - memcached
      - php-pecl-memcached
   tags: intall_memcached
