 - name: "vimrc cp"
   command: " cp -ip /etc/vimrc /etc/vimrc.org "
   tags: vimrc_cp

 - name: "vimrc add"
   lineinfile: dest='/etc/vimrc' line='{{item.add_value}}' backup=no
   with_items:
     - { add_value: 'set number' }
     - { add_value: 'set autoindent' }
   tags: vimrc_add