 - name: "vimrc cp"
   command: " cp -ip /etc/vimrc /etc/vimrc.org "
   tags: vimrc_cp

 - name: "vimrc add"
   lineinfile: dest='/etc/vimrc' line='{{item.add_value}}' backup=no
   with_items:
     - { add_value: 'set number' }
     - { add_value: 'set autoindent' }
     - { add_value: 'set encoding=utf-8'}
     - { add_value: 'set fileencoding=utf-8'}
     - { add_value: 'set fileencodings=utf-8,sjis,cp932,euc-jp,iso-2022-jp'}
     - { add_value: 'set fileformats=unix,dos,mac' }
   tags: vimrc_add
